apiVersion: 1

datasources:
  - name: Oru Postgres
    type: postgres
    access: proxy
    url: postgres:5432
    user: oru_user
    secureJsonData:
      password: oru_dev_password
    jsonData:
      database: oru_dev
      sslmode: disable
  - name: Redis Metrics
    type: redis-datasource
    access: proxy
    url: redis://redis:6379
    jsonData:
      client: standalone
      poolSize: 5
